stages:
  split:
    cmd: uv run src/exam_dvc/data/split_data.py
    deps:
    - data/raw_data/X_raw.csv
    - data/raw_data/y_raw.csv
    - src/exam_dvc/data/split_data.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: uv run src/exam_dvc/data/normalize_data.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - src/exam_dvc/data/normalize_data.py
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv
  grid_search:
    cmd: uv run src/exam_dvc/models/grid_search.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/y_train.csv
    - src/exam_dvc/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: uv run src/exam_dvc/models/train.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/exam_dvc/models/train.py
    outs:
    - models/best_model.pkl
  evaluate:
    cmd: uv run src/exam_dvc/models/evaluate.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/best_model.pkl
    - src/exam_dvc/models/evaluate.py
    metrics:
      - metrics/scores.json:
          cache: false
