[project]
name = "examen-dvc"
version = "0.1.0"
description = "Datascientest dvc exam."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "scikit-learn>=1.7.1",
]
